// Global variables
let selectedComponent = null;
let connections = [];
let isConnecting = false;
let startComponent = null;
let startPoint = null;
let tempLine = null;

// Component information
const componentInfo = {
    'xtal': {
        name: 'Crystal',
        description: 'Provides the clock signal for the 8284 clock generator.',
        pins: {
            'OUT': 'Clock output to 8284'
        }
    },
    '8284': {
        name: '8284 Clock Generator',
        description: 'Generates the clock signals and control signals for the 8086 CPU.',
        pins: {
            'CLK': 'Clock output to 8086',
            'RESET': 'Reset signal to 8086',
            'READY': 'Ready signal to 8086'
        }
    },
    '8086': {
        name: '8086 CPU',
        description: 'The Intel 8086 is a 16-bit microprocessor chip designed by Intel between early 1976 and June 8, 1978. It is the first member of the x86 family.',
        pins: {
            'AD0-AD15': 'Address/Data Bus (Multiplexed)',
            'A16-A19': 'Address Bus (High)',
            'RD': 'Read Signal',
            'WR': 'Write Signal',
            'M/IO': 'Memory/IO Signal',
            'CLK': 'Clock Input',
            'RESET': 'Reset Input',
            'READY': 'Ready Input',
            'S0-S2': 'Status Outputs'
        }
    },
    '8288': {
        name: '8288 Bus Controller',
        description: 'The 8288 Bus Controller generates all the bus control signals for the 8086 CPU. It derives control signals from the status signals generated by the 8086.',
        pins: {
            'ALE': 'Address Latch Enable',
            'DEN': 'Data Enable',
            'DT/R': 'Data Transmit/Receive',
            'IORC': 'I/O Read Control',
            'IOWC': 'I/O Write Control',
            'MEMR': 'Memory Read',
            'MEMW': 'Memory Write',
            'S0-S2': 'Status Inputs'
        }
    },
    'latches': {
        name: 'Address Latches',
        description: '8282/8283 Address Latches are used to demultiplex the address and data bus in the 8086 system.',
        pins: {
            'AD0-AD15': 'Address/Data Input',
            'A0-A15': 'Address Output',
            'ALE': 'Address Latch Enable',
            'OE': 'Output Enable'
        }
    },
    'databuffer': {
        name: 'Data Buffer',
        description: '8286 Data Buffer is used to increase the driving capability of the data bus in the 8086 system.',
        pins: {
            'D0-D15': 'Data Lines',
            'DT/R': 'Data Transmit/Receive',
            'DEN': 'Data Enable'
        }
    },
    'addressbus': {
        name: 'Address Bus',
        description: 'Bus that carries address signals from the latches to memory and I/O devices.',
        pins: {
            'A0-A19': 'Address Signals'
        }
    },
    'controlbus': {
        name: 'Control Bus',
        description: 'Bus that carries control signals from the 8288 bus controller to memory and I/O devices.',
        pins: {
            'RD': 'Read Signal',
            'WR': 'Write Signal',
            'MEMR': 'Memory Read',
            'MEMW': 'Memory Write',
            'IORC': 'I/O Read Control',
            'IOWC': 'I/O Write Control'
        },
        image: 'controlbus.png'
    },
    'databus': {
        name: 'Data Bus',
        description: 'Bidirectional bus that carries data between the CPU, memory, and I/O devices.',
        pins: {
            'D0-D15': 'Data Signals'
        }
    },
    'memory': {
        name: 'Memory',
        description: 'Memory storage for the 8086 system. Can be RAM or ROM depending on the system requirements.',
        pins: {
            'A0-A19': 'Address Lines',
            'D0-D15': 'Data Lines',
            'OE': 'Output Enable',
            'WE': 'Write Enable',
            'CS': 'Chip Select'
        }
    },
    'peripheral': {
        name: 'Peripheral',
        description: 'Input/Output devices connected to the 8086 system for communication with the external world.',
        pins: {
            'A0-A15': 'Address Lines',
            'D0-D15': 'Data Lines',
            'IOR': 'I/O Read',
            'IOW': 'I/O Write',
            'CS': 'Chip Select'
        }
    },
    'clk-gen': {
        name: 'Clock Generator',
        description: 'Generates the clock signals required for the operation of the 8086 microprocessor and other components.',
        pins: {
            'CLK': 'Clock Output',
            'RESET': 'Reset Signal',
            'READY': 'Ready Input'
        }
    },
    'latches': {
        name: 'Address Latches',
        description: '8282/8283 Address Latches are used to demultiplex the address and data bus in the 8086 system.',
        pins: {
            'AD0-AD15': 'Address/Data Input',
            'A0-A15': 'Address Output',
            'ALE': 'Address Latch Enable',
            'OE': 'Output Enable'
        }
    },
    'databuffer': {
        name: 'Data Buffer',
        description: '8286 Data Buffer is used to increase the driving capability of the data bus in the 8086 system.',
        pins: {
            'D0-D15': 'Data Lines',
            'DT/R': 'Data Transmit/Receive',
            'DEN': 'Data Enable'
        }
    },
    'addressbus': {
        name: 'Address Lines',
        description: 'Address bus lines used to specify memory or I/O addresses in the 8086 system.',
        pins: {
            'A0-A19': 'Address Signals'
        }
    },
    'datalines': {
        name: 'Data Lines',
        description: 'Bidirectional data bus lines used for data transfer between components in the 8086 system.',
        pins: {
            'D0-D15': 'Data Signals'
        }
    },
    'component2': {
        name: 'Additional Component',
        description: 'Additional component in the 8086 system architecture.',
        pins: {
            'PIN1': 'Pin 1',
            'PIN2': 'Pin 2',
            'PIN3': 'Pin 3'
        }
    }
};

// Correct connections for validation based on the diagram
const correctConnections = [
    // Clock Generator connections
    { from: '8284', to: '8086', signal: 'Reset,CLK,Ready' },
    { from: '8284', to: '8288', signal: 'CLK' },
    //{ from: '8284', to: '8086', signal: 'Clk' },
   // { from: '8284', to: '8086', signal: 'Ready' },
    
    // CPU to Bus Controller
    { from: '8086', to: '8288', signal: 'Status S₂S₁S₀' },
    
    // CPU to Bus Interface Logic
    { from: '8086', to: 'latches', signal: 'A₁₉-A₁₆, AD₁₅-AD₀' },
    { from: '8086', to: 'databuffer', signal: 'AD₁₅-AD₀' },
    
    // Bus Controller to Bus Interface Logic
    { from: '8288', to: 'latches', signal: 'ALE' },
    { from: '8288', to: 'databuffer', signal: 'DT/R,DEN' },
    //{ from: '8288', to: 'databuffer', signal: 'DEN' },
    
    // Bus Interface Logic to System Buses
    { from: 'latches', to: 'addressbus', signal: 'Address A₁₉-A₀' },
    { from: 'latches', to: 'databuffer', signal: 'A/D' },
    { from: 'databuffer', to: 'databus', signal: 'Data Bus' },
    
    // Bus Controller to Control Bus
    { from: '8288', to: 'controlbus', signal: 'MRDC, MWTC, IORC, IOWC' },
    
    // System Buses to System Devices
   // { from: 'addressbus', to: 'decoder', signal: 'Address' },
   // { from: 'decoder', to: 'memory', signal: 'CS' },
    //{ from: 'decoder', to: 'peripheral', signal: 'CS' },
    { from: 'addressbus', to: 'memory', signal: 'Address' },
    { from: 'addressbus', to: 'peripheral', signal: 'Address' },
    { from: 'databus', to: 'memory', signal: 'Data' },
    { from: 'databus', to: 'peripheral', signal: 'Data' },
    { from: 'databus', to: 'databuffer', signal: 'Data' },
    
    // Control Bus to System Devices
    { from: 'controlbus', to: 'memory', signal: 'RD (from MRDC),WR (from MWTC)' },
   // { from: 'controlbus', to: 'memory', signal: 'WR (from MWTC)' },
   // { from: 'controlbus', to: 'peripheral', signal: 'RD (from IORC)' },
    { from: 'controlbus', to: 'peripheral', signal: 'RD (from IORC),WR (from IOWC)' }
];

// Initialize the application
document.addEventListener('DOMContentLoaded', function() {
    initializeDragAndDrop();
    initializeButtons();
    initializeWorkspace();
});

// Initialize drag and drop functionality
function initializeDragAndDrop() {
    const components = document.querySelectorAll('.component');
    const workspace = document.getElementById('workspace-area');
    
    // Make components draggable
    components.forEach(component => {
        component.addEventListener('dragstart', dragStart);
        component.addEventListener('dragend', dragEnd);
    });
    
    // Set up workspace as drop target
    workspace.addEventListener('dragover', dragOver);
    workspace.addEventListener('dragenter', dragEnter);
    workspace.addEventListener('dragleave', dragLeave);
    workspace.addEventListener('drop', drop);
}

// Initialize buttons
function initializeButtons() {
    document.getElementById('clear-btn').addEventListener('click', clearWorkspace);
    document.getElementById('check-btn').addEventListener('click', checkConnections);
    document.getElementById('hint-btn').addEventListener('click', showHint);
}

// Initialize workspace
function initializeWorkspace() {
    const workspace = document.getElementById('workspace-area');
    workspace.addEventListener('click', handleWorkspaceClick);
}

// Drag and drop functions
function dragStart(e) {
    e.dataTransfer.setData('text/plain', e.target.dataset.component);
    setTimeout(() => {
        e.target.classList.add('dragging');
    }, 0);
}

function dragEnd(e) {
    e.target.classList.remove('dragging');
}

function dragOver(e) {
    e.preventDefault();
}

function dragEnter(e) {
    e.preventDefault();
    e.target.classList.add('drag-over');
}

function dragLeave(e) {
    e.target.classList.remove('drag-over');
}

function drop(e) {
    e.preventDefault();
    e.target.classList.remove('drag-over');

    const componentType = e.dataTransfer.getData('text/plain');
    if (componentType) {
        // Calculate mouse position relative to workspace
        const workspace = document.getElementById('workspace-area');
        const rect = workspace.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;
        createWorkspaceComponent(componentType, x, y);
    }
}

// Create component in workspace
function createWorkspaceComponent(componentType, x, y) {
    const workspace = document.getElementById('workspace-area');
    const component = document.createElement('div');
    component.className = 'workspace-component';
    component.dataset.component = componentType;
    component.style.left = (x - 60) + 'px';
    component.style.top = (y - 30) + 'px';
    
    // Add component content
    const img = document.createElement('img');
    img.src = componentInfo[componentType].image || (componentType + '.png');
    img.alt = componentInfo[componentType].name;
    img.width = 100;
    
    const name = document.createElement('p');
    name.textContent = componentInfo[componentType].name;
    
    component.appendChild(img);
    component.appendChild(name);
    
    // Add event listeners
    component.addEventListener('mousedown', startDragComponent);
    component.addEventListener('click', selectComponent);
    
    // Add connection points
    addConnectionPoints(component, componentType);
    
    workspace.appendChild(component);
}

// Add connection points to component
function addConnectionPoints(component, componentType) {
    // Left (input)
    const inputLeft = document.createElement('div');
    inputLeft.className = 'connection-point input';
    inputLeft.dataset.type = 'input';
    inputLeft.style.left = '-6px';
    inputLeft.style.top = '50%';
    component.appendChild(inputLeft);

    // Right (output)
    const outputRight = document.createElement('div');
    outputRight.className = 'connection-point output';
    outputRight.dataset.type = 'output';
    outputRight.style.right = '-6px';
    outputRight.style.top = '50%';
    component.appendChild(outputRight);

    // Top (input)
    const inputTop = document.createElement('div');
    inputTop.className = 'connection-point input';
    inputTop.dataset.type = 'input';
    inputTop.style.top = '-6px';
    inputTop.style.left = '50%';
    component.appendChild(inputTop);

    // Bottom (output)
    const outputBottom = document.createElement('div');
    outputBottom.className = 'connection-point output';
    outputBottom.dataset.type = 'output';
    outputBottom.style.bottom = '-6px';
    outputBottom.style.left = '50%';
    component.appendChild(outputBottom);

    // Add click handlers for connection points
    inputLeft.addEventListener('mousedown', startConnection);
    outputRight.addEventListener('mousedown', startConnection);
    inputTop.addEventListener('mousedown', startConnection);
    outputBottom.addEventListener('mousedown', startConnection);
}

// Component dragging in workspace
function startDragComponent(e) {
    if (e.target.classList.contains('connection-point')) return;
    
    const component = e.currentTarget;
    const startX = e.clientX;
    const startY = e.clientY;
    const startLeft = parseInt(component.style.left) || 0;
    const startTop = parseInt(component.style.top) || 0;
    
    function dragComponent(moveEvent) {
        const deltaX = moveEvent.clientX - startX;
        const deltaY = moveEvent.clientY - startY;
        component.style.left = (startLeft + deltaX) + 'px';
        component.style.top = (startTop + deltaY) + 'px';
        
        // Update any connections to this component
        updateConnections(component);
    }
    
    function stopDrag() {
        document.removeEventListener('mousemove', dragComponent);
        document.removeEventListener('mouseup', stopDrag);
    }
    
    document.addEventListener('mousemove', dragComponent);
    document.addEventListener('mouseup', stopDrag);
    
    e.preventDefault();
}

// Component selection
function selectComponent(e) {
    if (e.target.classList.contains('connection-point')) return;
    
    // Deselect previous component
    if (selectedComponent) {
        selectedComponent.classList.remove('selected');
    }
    
    // Select new component
    selectedComponent = e.currentTarget;
    selectedComponent.classList.add('selected');
    
    // Show component info
    showComponentInfo(selectedComponent.dataset.component);
}

// Show component information
function showComponentInfo(componentType) {
    const infoDiv = document.getElementById('component-info');
    const component = componentInfo[componentType];
    
    if (component) {
        let html = `<h3>${component.name}</h3>`;
        html += `<p>${component.description}</p>`;
        html += `<h4>Pins:</h4><ul>`;
        
        for (const [pin, description] of Object.entries(component.pins)) {
            html += `<li><strong>${pin}:</strong> ${description}</li>`;
        }
        
        html += `</ul>`;
        infoDiv.innerHTML = html;
    } else {
        infoDiv.innerHTML = '<p>Select a component to view details</p>';
    }
}

// Connection functions
function startConnection(e) {
    e.stopPropagation();
    
    const point = e.currentTarget;
    const component = point.parentElement;
    
    isConnecting = true;
    startComponent = component;
    startPoint = point;
    
    // Create temporary line
    createTempLine(e.clientX, e.clientY);
    
    // Add mouse move and up listeners
    document.addEventListener('mousemove', moveTempLine);
    document.addEventListener('mouseup', endConnection);
}

function createTempLine(x, y) {
    const svgNS = "http://www.w3.org/2000/svg";
    tempLine = document.createElementNS(svgNS, 'svg');
    tempLine.classList.add('connection-line');
    tempLine.style.position = 'absolute';
    tempLine.style.left = '0';
    tempLine.style.top = '0';
    tempLine.style.width = '100%';
    tempLine.style.height = '100%';
    tempLine.style.pointerEvents = 'none';
    tempLine.style.zIndex = '999'; // High z-index for temp line to be visible during dragging
    
    const workspace = document.getElementById('workspace-area');
    const workspaceRect = workspace.getBoundingClientRect();
    
    const line = document.createElementNS(svgNS, 'line');
    line.setAttribute('x1', getOffsetPosition(startComponent, startPoint).x);
    line.setAttribute('y1', getOffsetPosition(startComponent, startPoint).y);
    line.setAttribute('x2', x - workspaceRect.left);
    line.setAttribute('y2', y - workspaceRect.top);
    line.setAttribute('stroke', '#3498db');
    line.setAttribute('stroke-width', '3');
    
    tempLine.appendChild(line);
    document.getElementById('workspace-area').appendChild(tempLine);
}

function moveTempLine(e) {
    if (!isConnecting || !tempLine) return;
    
    const workspace = document.getElementById('workspace-area');
    const workspaceRect = workspace.getBoundingClientRect();
    
    const line = tempLine.querySelector('line');
    line.setAttribute('x2', e.clientX - workspaceRect.left);
    line.setAttribute('y2', e.clientY - workspaceRect.top);
}

function endConnection(e) {
    if (!isConnecting) return;
    
    isConnecting = false;
    
    // Remove temporary line
    if (tempLine) {
        tempLine.remove();
        tempLine = null;
    }
    
    // Remove event listeners
    document.removeEventListener('mousemove', moveTempLine);
    document.removeEventListener('mouseup', endConnection);
    
    // Check if we're connecting to another point
    const element = document.elementFromPoint(e.clientX, e.clientY);
    
    if (element && element.classList.contains('connection-point') && element !== startPoint) {
        const endComponent = element.parentElement;
        if (endComponent !== startComponent) {
            createConnection(startComponent, startPoint, endComponent, element);
        }
    }
}

function getOffsetPosition(component, point) {
    const workspace = document.getElementById('workspace-area');
    const workspaceRect = workspace.getBoundingClientRect();
    const componentRect = component.getBoundingClientRect();
    
    // Get the position of the component relative to the workspace
    const componentX = componentRect.left - workspaceRect.left;
    const componentY = componentRect.top - workspaceRect.top;
    
    // Get the position of the connection point relative to the component
    const pointRect = point.getBoundingClientRect();
    const pointX = pointRect.left - componentRect.left;
    const pointY = pointRect.top - componentRect.top;
    
    // Return the absolute position of the connection point
    return {
        x: componentX + pointX + pointRect.width/2,
        y: componentY + pointY + pointRect.height/2
    };
}

function createConnection(startComponent, startPoint, endComponent, endPoint) {
    const connection = {
        from: startComponent,
        to: endComponent,
        startPoint: startPoint,
        endPoint: endPoint
    };
    
    connections.push(connection);
    drawConnection(connection);
    updateConnectionStatus();
}

function drawConnection(connection) {
    const workspace = document.getElementById('workspace-area');
    const svgNS = "http://www.w3.org/2000/svg";
    
    const svg = document.createElementNS(svgNS, 'svg');
    svg.classList.add('connection-line');
    svg.style.position = 'absolute';
    svg.style.left = '0';
    svg.style.top = '0';
    svg.style.width = '100%';
    svg.style.height = '100%';
    svg.style.pointerEvents = 'none'; // Keep SVG non-interactive
    svg.style.zIndex = '15'; // Higher z-index: above components (10), below connection points (20)

    // Store connection reference for deletion
    svg.connectionRef = connection;

    // Create unique marker IDs for this connection to avoid conflicts
    const connectionId = Date.now() + Math.random().toString(36).substr(2, 9);
    const normalMarkerId = `arrow-${connectionId}`;
    const hoverMarkerId = `arrow-hover-${connectionId}`;

    // Create defs section with markers directly in this SVG
    const defs = document.createElementNS(svgNS, 'defs');
    
    // Create the normal arrow marker
    const marker = document.createElementNS(svgNS, 'marker');
    marker.setAttribute('id', normalMarkerId);
    marker.setAttribute('markerWidth', '20');
    marker.setAttribute('markerHeight', '20');
    marker.setAttribute('refX', '18');
    marker.setAttribute('refY', '10');
    marker.setAttribute('orient', 'auto');
    marker.setAttribute('markerUnits', 'userSpaceOnUse');
    marker.setAttribute('viewBox', '0 0 20 20');
    
    const arrowPath = document.createElementNS(svgNS, 'path');
    // Much larger and more visible arrow with thick stroke
    arrowPath.setAttribute('d', 'M2,2 L2,18 L18,10 Z');
    arrowPath.setAttribute('fill', '#3498db');
    arrowPath.setAttribute('stroke', '#2980b9');
    arrowPath.setAttribute('stroke-width', '2');
    
    marker.appendChild(arrowPath);
    defs.appendChild(marker);
    
    // Create the hover arrow marker
    const hoverMarker = document.createElementNS(svgNS, 'marker');
    hoverMarker.setAttribute('id', hoverMarkerId);
    hoverMarker.setAttribute('markerWidth', '20');
    hoverMarker.setAttribute('markerHeight', '20');
    hoverMarker.setAttribute('refX', '18');
    hoverMarker.setAttribute('refY', '10');
    hoverMarker.setAttribute('orient', 'auto');
    hoverMarker.setAttribute('markerUnits', 'userSpaceOnUse');
    hoverMarker.setAttribute('viewBox', '0 0 20 20');
    
    const hoverArrowPath = document.createElementNS(svgNS, 'path');
    hoverArrowPath.setAttribute('d', 'M2,2 L2,18 L18,10 Z');
    hoverArrowPath.setAttribute('fill', '#e74c3c');
    hoverArrowPath.setAttribute('stroke', '#c0392b');
    hoverArrowPath.setAttribute('stroke-width', '2');
    
    hoverMarker.appendChild(hoverArrowPath);
    defs.appendChild(hoverMarker);
    
    svg.appendChild(defs);

    console.log('Created markers with IDs:', normalMarkerId, hoverMarkerId);

    const path = document.createElementNS(svgNS, 'path');

    // Get positions
    const startPos = getOffsetPosition(connection.from, connection.startPoint);
    const endPos = getOffsetPosition(connection.to, connection.endPoint);

    // Create path data
    const pathData = `M ${startPos.x} ${startPos.y} L ${endPos.x} ${endPos.y}`;
    path.setAttribute('d', pathData);
    path.setAttribute('stroke', '#3498db');
    path.setAttribute('stroke-width', '8'); // Make line thicker for easier clicking
    path.setAttribute('fill', 'none');
    path.setAttribute('marker-end', `url(#${normalMarkerId})`); // Use unique marker ID
    path.style.cursor = 'pointer';
    path.style.pointerEvents = 'auto'; // Only the path is clickable

    console.log('Set marker-end to:', `url(#${normalMarkerId})`);

    // Add hover effects
    path.addEventListener('mouseenter', function() {
        path.setAttribute('stroke', '#e74c3c'); // Red on hover
        path.setAttribute('stroke-width', '10');
        path.setAttribute('marker-end', `url(#${hoverMarkerId})`); // Use red arrow on hover
    });

    path.addEventListener('mouseleave', function() {
        path.setAttribute('stroke', '#3498db'); // Back to blue
        path.setAttribute('stroke-width', '8');
        path.setAttribute('marker-end', `url(#${normalMarkerId})`); // Back to blue arrow
    });

    // Add click event to delete connection
    path.addEventListener('click', function(e) {
        e.stopPropagation();
        e.preventDefault();
        deleteConnection(connection, svg);
    });

    svg.appendChild(path);
    workspace.appendChild(svg);
}

function deleteConnection(connection, svgElement) {
    try {
        // Confirm deletion
        if (confirm('Delete this connection?')) {
            // Remove from connections array
            const index = connections.indexOf(connection);
            if (index > -1) {
                connections.splice(index, 1);
            }
            
            // Remove the SVG element from DOM
            if (svgElement && svgElement.parentNode) {
                svgElement.remove();
            }
            
            // Update connection status
            updateConnectionStatus();
        }
    } catch (error) {
        console.error('Error deleting connection:', error);
    }
}

function updateConnectionStatus() {
    try {
        const status = document.getElementById('connection-status');
        if (!status) return; // Exit if element doesn't exist
        
        if (connections.length === 0) {
            status.textContent = 'No connections made';
            status.style.backgroundColor = '#f8f9fa';
        } else {
            status.textContent = `${connections.length} connection(s) made. Click Check Connections to validate.`;
            status.style.backgroundColor = '#f8f9fa';
        }
    } catch (error) {
        console.error('Error updating connection status:', error);
    }
}

function updateConnections(component) {
    // Find all connections that involve this component
    const componentConnections = connections.filter(conn =>
        conn.from === component || conn.to === component
    );
    
    // Remove existing connection lines
    document.querySelectorAll('.connection-line').forEach(line => line.remove());
    
    // Redraw all connections
    connections.forEach(conn => drawConnection(conn));
}

// Button functions
function clearWorkspace() {
    if (confirm('Are you sure you want to clear the workspace?')) {
        const workspace = document.getElementById('workspace-area');
        const components = workspace.querySelectorAll('.workspace-component');
        const lines = workspace.querySelectorAll('.connection-line');
        
        components.forEach(component => component.remove());
        lines.forEach(line => line.remove());
        
        connections = [];
        selectedComponent = null;
        
        document.getElementById('component-info').innerHTML = '<p>Select a component to view details</p>';
        updateConnectionStatus();
    }
}

function checkConnections() {
    const status = document.getElementById('connection-status');
    
    if (connections.length === 0) {
        status.textContent = 'No connections to check. Create some connections first.';
        status.style.backgroundColor = '#f8f9fa';
        return;
    }

    // Map workspace connections to component names
    const userConnections = connections.map(conn => ({
        from: conn.from.dataset.component,
        to: conn.to.dataset.component
    }));

    // Check each user connection against correctConnections
    let correctCount = 0;
    let feedback = [];
    userConnections.forEach((uc, idx) => {
        const match = correctConnections.find(cc =>
            cc.from === uc.from && cc.to === uc.to
        );
        if (match) {
            correctCount++;
            feedback.push(`<span style="color:green;">✔ ${uc.from} → ${uc.to}</span><br>&nbsp;&nbsp;&nbsp;<em style="color:#27ae60;">Signal: ${match.signal}</em>`);
        } else {
            // Check if there's a reverse connection or find suggested signal
            const reverseMatch = correctConnections.find(cc =>
                cc.from === uc.to && cc.to === uc.from
            );
            if (reverseMatch) {
                feedback.push(`<span style="color:orange;">⚠ ${uc.from} → ${uc.to}</span><br>&nbsp;&nbsp;&nbsp;<em style="color:#f39c12;">Try: ${uc.to} → ${uc.from} (Signal: ${reverseMatch.signal})</em>`);
            } else {
                feedback.push(`<span style="color:red;">✖ ${uc.from} → ${uc.to}</span><br>&nbsp;&nbsp;&nbsp;<em style="color:#e74c3c;">No valid signal found for this connection</em>`);
            }
        }
    });

    const percentage = Math.round((correctCount / correctConnections.length) * 100);

    // Find missing connections
    const missingConnections = correctConnections.filter(cc => {
        return !userConnections.some(uc => uc.from === cc.from && uc.to === cc.to);
    });

    let missingConnectionsHtml = '';
    if (missingConnections.length > 0) {
        missingConnectionsHtml = `
            <br><strong>Missing Connections:</strong><br>
            <div style="line-height: 1.6; color: #7f8c8d;">
                ${missingConnections.map(mc => 
                    `<span>⚪ ${mc.from} → ${mc.to}</span><br>&nbsp;&nbsp;&nbsp;<em>Signal: ${mc.signal}</em>`
                ).join('<br><br>')}
            </div>
        `;
    }

    status.innerHTML = `
        <strong>Connection Check Results:</strong><br>
        Total connections: ${connections.length}<br>
        Correct connections: ${correctCount}<br>
        Expected connections: ${correctConnections.length}<br>
        Estimated correctness: ${percentage}%<br><br>
        <div style="line-height: 1.6;">${feedback.join('<br><br>')}</div>
        ${missingConnectionsHtml}
        <div style="font-size: 0.9em; margin-top: 15px; padding-top: 10px; border-top: 1px solid #ddd;">
            <strong>Legend:</strong><br>
            <span style="color:green;">✔ Correct connection with signal type</span><br>
            <span style="color:orange;">⚠ Wrong direction (suggestion provided)</span><br>
            <span style="color:red;">✖ Invalid connection</span><br>
            <span style="color:#7f8c8d;">⚪ Missing connection</span><br>
            <em>Reference: 8086_system_diagram.md</em>
        </div>
    `;

    if (percentage >= 80) {
        status.style.backgroundColor = '#d4edda';
    } else if (percentage >= 50) {
        status.style.backgroundColor = '#fff3cd';
    } else {
        status.style.backgroundColor = '#f8d7da';
    }
}

function showHint() {
    // Create a modal-style hint display
    const hintModal = document.createElement('div');
    hintModal.style.position = 'fixed';
    hintModal.style.top = '0';
    hintModal.style.left = '0';
    hintModal.style.width = '100%';
    hintModal.style.height = '100%';
    hintModal.style.backgroundColor = 'rgba(0, 0, 0, 0.7)';
    hintModal.style.zIndex = '1000';
    hintModal.style.display = 'flex';
    hintModal.style.justifyContent = 'center';
    hintModal.style.alignItems = 'center';
    
    const hintContent = document.createElement('div');
    hintContent.style.backgroundColor = 'white';
    hintContent.style.padding = '20px';
    hintContent.style.borderRadius = '10px';
    hintContent.style.maxWidth = '800px';
    hintContent.style.maxHeight = '80%';
    hintContent.style.overflow = 'auto';
    hintContent.style.textAlign = 'center';
    hintContent.style.boxShadow = '0 4px 20px rgba(0, 0, 0, 0.3)';
    
    hintContent.innerHTML = `
        <h2>8086 Architecture Hint</h2>
        <p>Here's where to start - the Crystal component:</p>
        <img src="xtal.png" alt="Crystal Component" style="max-width: 100%; height: auto; margin: 20px 0;">
        <p>Start by placing the Crystal component first, then add the 8284 Clock Generator and connect them. The crystal provides the clock signal for the entire 8086 system.</p>
        <button id="close-hint" style="margin-top: 20px; padding: 10px 20px; background-color: #3498db; color: white; border: none; border-radius: 5px; cursor: pointer;">Close</button>
    `;
    
    hintModal.appendChild(hintContent);
    document.body.appendChild(hintModal);
    
    // Close hint when clicking the close button or outside the modal
    document.getElementById('close-hint').addEventListener('click', function() {
        document.body.removeChild(hintModal);
    });
    
    hintModal.addEventListener('click', function(e) {
        if (e.target === hintModal) {
            document.body.removeChild(hintModal);
        }
    });
}

// Handle workspace clicks
function handleWorkspaceClick(e) {
    // If clicking on empty space, deselect component
    if (e.target === document.getElementById('workspace-area') || e.target.classList.contains('grid')) {
        if (selectedComponent) {
            selectedComponent.classList.remove('selected');
            selectedComponent = null;
            document.getElementById('component-info').innerHTML = '<p>Select a component to view details</p>';
        }
    }
}